title: Asish Ghoshal
description: Personal webpage.

url: http://asishgeek.github.io
baseurl: ""
paginate_path: "/blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index
 - title: About
   url: /about
 - title: Research
   url: /publications
 - title: Blog
   url: /blog/index.html

social:
   github: 
   twitter: 
   facebook: 
   email: a[full last name]@gmail.com

google_analytics: UA-73077954-1
